version: "3.4"
services:
  vite:
    container_name: vite
    image: node:16-alpine
    working_dir: /app/
    entrypoint: /bin/sh
    ports:
      - "${VITE_PORT:-3000}:3000"
    volumes:
      - ./:/app
    tty: true
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./dist/:/usr/share/nginx/html
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - vite