<template>
  <div>
    <h1>Vue Excel Export App</h1>
    <Modal :columns="d.columns" :data="e.items" />
  </div>
</template>

<script setup>
import Modal from "./components/Modal.vue";

const d = {
  title: "Учет использования дез. средств",
  columns: [
    {
      title: "Дата приготовления раствора",
      dataIndex: "preparation_date",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "calendar",
    },
    {
      title: "Средство",
      dataIndex: "disinfectant_id",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Помещение",
      dataIndex: "room_id",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Вид обработки",
      dataIndex: "clean_type",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filters: [
        {
          text: "Генеральная уборка",
          value: 1,
        },
        {
          text: "Влажная уборка",
          value: 2,
        },
      ],
      filterMultiple: !1,
    },
    {
      title: "Норма расхода",
      dataIndex: "norma",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Объем препарата",
      dataIndex: "volume",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Примечание к виду обработки",
      dataIndex: "comment",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Концентрация",
      dataIndex: "concentration",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Израсходавно",
      dataIndex: "spent",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
    {
      title: "Время создания записи",
      dataIndex: "created_at",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "calendar",
    },
    {
      title: "Время последнего изменения записи",
      dataIndex: "updated_at",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "calendar",
    },
    {
      title: "Автор последнего изменения",
      dataIndex: "updated_by",
      sorter: !0,
      minWidth: 100,
      width: 300,
      filterType: "text",
    },
  ],
  editRule: "d.locations.edit",
  actions: ["edit", "delete"],
  entityName: "filials",
  createBtn: true,
  values: {
    company_id: (column, text, record) => {
      return record.company.name;
    },
  },
  relations: ["company"],
  expandData: [
    {
      name: "id",
      value: (record) => {
        return record.id;
      },
    },
    {
      name: "Название",
      value: "name",
    },
    {
      name: "Предприятие",
      value: (record) => {
        return record.company.name;
      },
    },
  ],
};

const e = {
  items: [
    {
      id: 164,
      subdivision_id: 6,
      created_at: "2024-01-29 09:17:32",
      updated_at: "2024-01-29 09:17:32",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 2,
      comment: null,
      norma: 100,
      volume: 25,
      preparation_date: "2024-01-29",
      room_id: 2215,
      ref_table: null,
      ref_id: null,
      area: 135,
      spent: 33.75,
      concentration: 25,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2215,
        subdivision_id: 6,
        name: "Лабораторный зал №1(бх-имуннология)",
        humidity_flag: 1,
        general_area: 400,
        volume: 135,
        area: 165,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 161,
      subdivision_id: 6,
      created_at: "2024-01-28 11:36:26",
      updated_at: "2024-01-28 11:36:26",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-28",
      room_id: 891,
      ref_table: "disinfectant",
      ref_id: 346,
      area: 461,
      spent: 230.5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 891,
        subdivision_id: 6,
        name: "лабораторный зал №1",
        humidity_flag: 1,
        general_area: 600,
        volume: 461,
        area: 250,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 111,
      subdivision_id: 6,
      created_at: "2024-01-26 10:18:03",
      updated_at: "2024-01-26 10:18:03",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 2,
      comment: null,
      norma: 100,
      volume: 25,
      preparation_date: "2024-01-26",
      room_id: 2215,
      ref_table: null,
      ref_id: null,
      area: 135,
      spent: 33.75,
      concentration: 25,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2215,
        subdivision_id: 6,
        name: "Лабораторный зал №1(бх-имуннология)",
        humidity_flag: 1,
        general_area: 400,
        volume: 135,
        area: 165,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 104,
      subdivision_id: 6,
      created_at: "2024-01-25 11:22:56",
      updated_at: "2024-01-25 11:22:56",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-25",
      room_id: 2228,
      ref_table: "disinfectant",
      ref_id: 289,
      area: 10,
      spent: 5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2228,
        subdivision_id: 6,
        name: "Утиль",
        humidity_flag: 1,
        general_area: 75,
        volume: 10,
        area: 30,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 101,
      subdivision_id: 6,
      created_at: "2024-01-24 08:17:35",
      updated_at: "2024-01-24 08:17:35",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-24",
      room_id: 2228,
      ref_table: "disinfectant",
      ref_id: 281,
      area: 10,
      spent: 5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2228,
        subdivision_id: 6,
        name: "Утиль",
        humidity_flag: 1,
        general_area: 75,
        volume: 10,
        area: 30,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 100,
      subdivision_id: 6,
      created_at: "2024-01-24 08:17:16",
      updated_at: "2024-01-24 08:17:16",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-24",
      room_id: 2228,
      ref_table: "disinfectant",
      ref_id: 280,
      area: 10,
      spent: 5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2228,
        subdivision_id: 6,
        name: "Утиль",
        humidity_flag: 1,
        general_area: 75,
        volume: 10,
        area: 30,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 80,
      subdivision_id: 6,
      created_at: "2024-01-21 18:05:30",
      updated_at: "2024-01-21 18:05:30",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-21",
      room_id: 2215,
      ref_table: "disinfectant",
      ref_id: 256,
      area: 135,
      spent: 67.5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2215,
        subdivision_id: 6,
        name: "Лабораторный зал №1(бх-имуннология)",
        humidity_flag: 1,
        general_area: 400,
        volume: 135,
        area: 165,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 70,
      subdivision_id: 6,
      created_at: "2024-01-18 21:52:29",
      updated_at: "2024-01-18 21:52:29",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-18",
      room_id: 2225,
      ref_table: "disinfectant",
      ref_id: 239,
      area: 13,
      spent: 6.5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2225,
        subdivision_id: 6,
        name: "Цитология №2",
        humidity_flag: 1,
        general_area: 80,
        volume: 13,
        area: 35,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 69,
      subdivision_id: 6,
      created_at: "2024-01-18 21:52:08",
      updated_at: "2024-01-18 21:52:08",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-18",
      room_id: 2223,
      ref_table: "disinfectant",
      ref_id: 238,
      area: 18,
      spent: 9,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 2223,
        subdivision_id: 6,
        name: "Цитология №1",
        humidity_flag: 1,
        general_area: 90,
        volume: 18,
        area: 40,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
    {
      id: 52,
      subdivision_id: 6,
      created_at: "2024-01-12 21:11:32",
      updated_at: "2024-01-12 21:11:32",
      created_by: 200,
      updated_by: 200,
      disinfectant_id: 17,
      clean_type: 1,
      comment: null,
      norma: 100,
      volume: 50,
      preparation_date: "2024-01-12",
      room_id: 891,
      ref_table: "disinfectant",
      ref_id: 196,
      area: 461,
      spent: 230.5,
      concentration: 50,
      createdBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      updatedBy: {
        id: 200,
        username: "s.temirova",
        email: "s.temirova@kdlolymp.kz",
        created_at: "2024-01-09 06:53:10",
        updated_at: "2024-01-09 06:53:10",
        f: "Севила",
        i: "Темирова",
        o: "",
        phone: null,
        status: 10,
        fio: "Севила Темирова ",
      },
      room: {
        id: 891,
        subdivision_id: 6,
        name: "лабораторный зал №1",
        humidity_flag: 1,
        general_area: 600,
        volume: 461,
        area: 250,
        active: 1,
      },
      disinfectant: {
        id: 17,
        unit_id: 2,
        name: "Фармдезин Амино",
        wet_rate: 25,
        general_rate: 50,
        active: 1,
        norma: 100,
        state: 1,
      },
    },
  ],
};
</script>
